# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Function_Plotter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_FunctionPlotter(object):
    def setupUi(self, FunctionPlotter):
        FunctionPlotter.setObjectName("FunctionPlotter")
        FunctionPlotter.resize(490, 346)
        self.centralwidget = QtWidgets.QWidget(FunctionPlotter)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl1.setFont(font)
        self.lbl1.setObjectName("lbl1")
        self.horizontalLayout.addWidget(self.lbl1)
        self.txt1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt1.setObjectName("txt1")
        self.horizontalLayout.addWidget(self.txt1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl2.setFont(font)
        self.lbl2.setObjectName("lbl2")
        self.horizontalLayout_2.addWidget(self.lbl2)
        self.txt2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt2.setObjectName("txt2")
        self.horizontalLayout_2.addWidget(self.txt2)
        self.lbl3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl3.setFont(font)
        self.lbl3.setObjectName("lbl3")
        self.horizontalLayout_2.addWidget(self.lbl3)
        self.txt3 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt3.setObjectName("txt3")
        self.horizontalLayout_2.addWidget(self.txt3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.lbl4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl4.setFont(font)
        self.lbl4.setObjectName("lbl4")
        self.gridLayout.addWidget(self.lbl4, 2, 0, 1, 1)
        self.lbl5 = QtWidgets.QLabel(self.centralwidget)
        self.lbl5.setObjectName("lbl5")
        self.gridLayout.addWidget(self.lbl5, 3, 0, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        FunctionPlotter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FunctionPlotter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 26))
        self.menubar.setObjectName("menubar")
        FunctionPlotter.setMenuBar(self.menubar)

        self.retranslateUi(FunctionPlotter)
        QtCore.QMetaObject.connectSlotsByName(FunctionPlotter)

    def retranslateUi(self, FunctionPlotter):
        _translate = QtCore.QCoreApplication.translate
        FunctionPlotter.setWindowTitle(_translate("FunctionPlotter", "Function Plotter"))
        self.lbl1.setText(_translate("FunctionPlotter", "F(X) = "))
        self.lbl2.setText(_translate("FunctionPlotter", "MIN = "))
        self.lbl3.setText(_translate("FunctionPlotter", "MAX = "))
        self.lbl4.setText(_translate("FunctionPlotter", "Some Useful Guidance:"))
        self.lbl5.setText(_translate("FunctionPlotter", "<html><head/><body><p>1. The only variable you shoud use is <span style=\" font-weight:600; text-decoration: underline;\">x</span>.</p><p>2. You can use + - / * ^ operator.</p><p>3. Function format:</p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">5*x^3 + 2*x</span></p></body></html>"))
        self.btn1.setText(_translate("FunctionPlotter", "Plot"))


def appGUI():
    app = QtWidgets.QApplication(sys.argv)
    FunctionPlotter = QtWidgets.QMainWindow()
    ui = Ui_FunctionPlotter()
    ui.setupUi(FunctionPlotter)

    return ui, app, FunctionPlotter
    # sys.exit(app.exec_())
